#!/bin/bash

# Script desarollado para la ejecución de rastreo de puertos habitual
# By c1pitri4
# Script pensado para uso ético y siempre con uso autorizado.

# Colores
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

# Función CTRL+C 

function ctrl_c(){
 echo -e "\n\n${purpleColour}[+]${endColour}${grayColour} Saliendo...\n${endColour}"
 tput cnorm && exit 1
   }

# Atrapar el Ctrl+C

trap ctrl_c SIGINT

# Permiso root

sudo -v

# Recibimos la IP a través del primer argumento.

IP=$1

# Función para el primer escaneo nmap (más silencioso y rápido)

silent_scan() {
    sudo nmap -sS --min-rate 5000 -n -p- --open -Pn -oG rawscan $IP > /dev/null
    firstscan=$(grep -oP '\d+(?=/open)' rawscan | paste -sd,)
    nmap -sC -sV -n -p$firstscan $IP -oG cleanscan -oN detailedscan > /dev/null

    cleanscan=$( (echo "PUERTO|SERVICIO|VERSION"; grep "Ports:" cleanscan | awk -F'Ports: ' '{print $2}' | tr -d ' ' | tr ',' '\n' | awk -F'/' '{print $1"|"$5"|"$7}') \
        | column -t -s'|' \
        | awk -v purple="$(echo -e "$purpleColour")" -v gray="$(echo -e "$grayColour")" -v end="$(echo -e "$endColour")" \
            'NR==1 { print purple $0 end; next } { print gray $0 end }' )

    echo -e "\n${purpleColour}[+]${endColour}${grayColour} Estos son los puertos abiertos con sus servicios escaneados:${endColour}\n${cleanscan}"
    echo -e "\n${purpleColour}[+]${endColour}${grayColour} Para ver más detalles, consulta el archivo creado${endColour}${purpleColour} detailedscan${endColour}"
}

# Validación de argumento y ejecución de funciones.

if [ "$IP" ]; then
  silent_scan &
      pid=$!

    spin=(. .. ... .. .)
    i=0
    while kill -0 $pid 2>/dev/null; do
      tput civis
        echo -ne "\r${purpleColour}[+]${endColour}${grayColour} Escaneando puertos${spin[i]}   "${endColour}
        i=$(( (i+1) % ${#spin[@]} ))
        sleep 0.3
    done
      tput cnorm
      rm -f rawscan cleanscan
else
  echo -e "\n${purpleColour}[!]${endColour}${grayColour} Uso:${endColour}"
  echo -e "\n${purpleColour}$0${endColour}${grayColour} <Direccion IP a escanear>${endColour}"
fi
